spring.application.name=spring-gift
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
jwt.secret=${JWT_SECRET}
spring.mvc.hiddenmethod.filter.enabled=true

spring.config.import=optional:file:.env[.properties]
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.client-secret=${KAKAO_CLIENT_SECRET}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}

resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.kakaoAuthClient.baseConfig=default